// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;

namespace Fusap.TimeSheet.Domain.TimeSheetAggregate.Entities
{
    /// <summary>
    /// It is Registration Table  RegistrationID
    /// </summary>
    public partial class AssignedRoles
    {
        public int AssignedRolesId { get; set; }
        public int? AssignToAdmin { get; set; }
        public string Status { get; set; }
        public DateTime? CreatedOn { get; set; }
        public int? CreatedBy { get; set; }
        public int? RegistrationId { get; set; }
    }
}
