// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;

namespace Fusap.TimeSheet.Domain.TimeSheetAggregate.Entities
{
    public partial class AssignedProjectToUsers
    {
        public int AssignedProjectToUsersId { get; set; }
        public int? ProjectId { get; set; }
        public int? RegistrationId { get; set; }
        public DateTime? CreatedOn { get; set; }
        public int? CreatedBy { get; set; }
    }
}
