// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;

namespace Fusap.TimeSheet.Domain.TimeSheetAggregate.Entities
{
    public partial class DescriptionTb
    {
        public int DescriptionId { get; set; }
        public string Description { get; set; }
        public int? ProjectId { get; set; }
        public int? TimeSheetMasterId { get; set; }
        public DateTime? CreatedOn { get; set; }
        public int? UserId { get; set; }
    }
}
