// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;

namespace Fusap.TimeSheet.Domain.TimeSheetAggregate.Entities
{
    public partial class ExpenseAuditTb
    {
        public int ApprovaExpenselLogId { get; set; }
        public int? ApprovalUser { get; set; }
        public DateTime? ProcessedDate { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string Comment { get; set; }
        public int? Status { get; set; }
        public int? ExpenseId { get; set; }
        public int? UserId { get; set; }
    }
}
