// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;

namespace Fusap.TimeSheet.Domain.TimeSheetAggregate.Entities
{
    public partial class MevetoState
    {
        public int MevetoStateId { get; set; }
        public string MevetoStateUuid { get; set; }
        public DateTime? CreatedOn { get; set; }
    }
}
