// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;

namespace Fusap.TimeSheet.Domain.TimeSheetAggregate.Entities
{
    public partial class MevetoLogin
    {
        public int MevetoLoginId { get; set; }
        public int RegistrationId { get; set; }
        public string MevetoId { get; set; }
        public DateTime? LastLoggedIn { get; set; }
        public DateTime? LastLoggedOut { get; set; }
        public DateTime? CreatedOn { get; set; }

        public virtual Registration Registration { get; set; }
    }
}
