// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;

namespace Fusap.TimeSheet.Domain.TimeSheetAggregate.Entities
{
    public partial class NotificationsTb
    {
        public int NotificationsId { get; set; }
        public string Status { get; set; }
        public string Message { get; set; }
        public DateTime? CreatedOn { get; set; }
        public DateTime? FromDate { get; set; }
        public DateTime? ToDate { get; set; }
    }
}
