// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace Fusap.TimeSheet.Domain.TimeSheetAggregate.Entities
{
    public partial class ProjectMaster
    {
        public int ProjectId { get; set; }
        public string ProjectName { get; set; }
        public string NatureofIndustry { get; set; }
        public string ProjectCode { get; set; }
    }
}
