// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Fusap.TimeSheet.Domain.TimeSheetAggregate.Entities
{
    public partial class Registration
    {
        public Registration()
        {
            MevetoLogin = new HashSet<MevetoLogin>();
        }

        public int RegistrationId { get; set; }
        public string Name { get; set; }
        public string Mobileno { get; set; }
        public string EmailId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }
        public string Gender { get; set; }
        public DateTime? Birthdate { get; set; }
        public int? RoleId { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string EmployeeId { get; set; }
        public DateTime? DateofJoining { get; set; }
        public int? ForceChangePassword { get; set; }

        public virtual ICollection<MevetoLogin> MevetoLogin { get; set; }
    }
}
