// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace Fusap.TimeSheet.Domain.TimeSheetAggregate.Entities
{
    public partial class Roles
    {
        public int RoleId { get; set; }
        public string Rolename { get; set; }
    }
}
