// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;

namespace Fusap.TimeSheet.Domain.TimeSheetAggregate.Entities
{
    public partial class TimeSheetDetails
    {
        public int TimeSheetId { get; set; }
        public string DaysofWeek { get; set; }
        public decimal? Hours { get; set; }
        public DateTime? Period { get; set; }
        public int? ProjectId { get; set; }
        public int? UserId { get; set; }
        public DateTime? CreatedOn { get; set; }
        public int? TimeSheetMasterId { get; set; }
        public decimal? TotalHours { get; set; }
    }
}
