// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;

namespace Fusap.TimeSheet.Domain.TimeSheetAggregate.Entities
{
    public partial class TimeSheetMaster
    {
        public int TimeSheetMasterId { get; set; }
        public DateTime? FromDate { get; set; }
        public DateTime? ToDate { get; set; }
        public decimal? TotalHours { get; set; }
        public int? UserId { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string Comment { get; set; }
        public int? TimeSheetStatus { get; set; }
    }
}
